### ISSUE TITLE
[organizer] keep filters and sorts when a proposal page is refreshed

### ISSUE THREAD

**Issue by ghost** [bpetetot/conference-hall-beta#178]
Lorsque je recharge la page de consultation d'un talk à noter, les boutons previous next ne sont plus actifs

(l'upload d'image ne marche pas :'(, je te mail cela )

**Comment by bpetetot** [comment]
![unnamed](https://user-images.githubusercontent.com/516360/36903463-13d16fc0-1e2e-11e8-94c1-994fced10c69.png)

**Comment by hgwood** [comment]
I've looked into this. The problem stems from the `<Ratings>` component requiring all proposals to be available in the app state (its containers calls `store.data.proposals.getKeys()`), as well as the index of the proposal being reviewed relative to those proposals (the container calls `{ proposalIndex } = store.ui.organizer.proposal.get()`). While the components *requires* those, it does not attempt to load them if they are not available.

After reading a fair chunk of the app's code, I think that components usually request data using actions that have a type of the form `@@ui/ON_LOAD_*`. However, in the case at hand I could not use `@@ui/ON_LOAD_EVENT_PROPOSALS` because it *forces* data to be retrieved from the server, and that's not what I want (well, it works but it's inefficient). Sometimes `ON_LOAD` actions behave that way (`ON_LOAD_RATINGS` does that too) but sometimes they do not (`ON_LOAD_PROPOSAL` checks for local presence of the data and only retrieves it from the server if required).

There might be a need to define a consistent convention for components to request data. For instance, maybe `ON_LOAD` actions could always return local data unless the payload has a specific flag (`forceReload`?) set to `true`.

Here is what data the `<Ratings>` components actually requires and what it assumes about its origin:
- the rating for the proposal is assumed to be retrieved by the parent `<Proposal>`
- the proposals are assumed to have been retrieved by `<Proposals>` at an earlier time
- the proposal index is assumed to have been computed by a reaction to an action dispatched by `<Proposals>` at an earlier time

With the convention proposed above, `<Ratings>` would emit 3 `ON_LOAD` actions, one for each of these pieces of data, instead of assuming the data is present.

What do you think @bpetetot?

**Comment by bpetetot** [comment]
There are 2 issues in that case : 
* **first**, as you said @hgwood, `<Ratings />` component doesn't fetch the data, it assumes that it's already in the store. And I'm agree, there is a lack of consistency with action names in the app, between getting data from the local store and fetching data from the remote database.
* **second**, even if `<Ratings />` component fetches the data, it will always fetch all the proposals after refreshing. But we could have filters / sort applied in proposals before refreshing. And the user wants to rates only proposals applied by its filters (and keep it when refreshing)

**So I see 3 steps (issues), to fix this :** 
1. Keep current filters in the router URL `/organizer/event/:id/proposals` (as @hgwood do for sort order in #180)
2. Extends this behaviour to router URL `/organizer/event/:id/proposal/:id`. Because `next` and `previous` buttons must keep filtered/sorted proposals list. And refreshing it, will fetch the data.
3. Refactoring, @hgwood has right, there is  a lack of consistency in actions names and their behaviours. And it must be harmonised in the whole app and done in a different issue

@hgwood do you think this is a good approach ?

**Comment by hgwood** [comment]
Yes. 💯

**Comment by hgwood** [comment]
I've started working on step 1.

**Comment by bpetetot** [comment]
Filters and sort issues fixes by PRs #187 and #196 
Refactoring part will be treated with issue #214
