### ISSUE TITLE
unable to login (in order to submit a talk)

### ISSUE THREAD

**Issue by iamdey** [bpetetot/conference-hall-beta#241]
![cfp_bug_login_devfest](https://user-images.githubusercontent.com/65737/40776423-fcc4bfce-64ca-11e8-831c-ad4a1f92c422.gif)

I disabled ublock origin.

I'm not fully sure that my browser is clean, i'll try asap after a full restart.

**Comment by bpetetot** [comment]
Thanks for the report, I'm going to investigate ;)

**Comment by bpetetot** [comment]
Hi @iamdey, it seems that's a Firebase Auth system issue due to t 3rd party cookies blocked by the browser, you can see resources about it here:
- https://github.com/firebase/firebase-js-sdk/issues/865
- https://www.reddit.com/r/Firebase/comments/5ovejp/why_cant_firebase_authentication_work_when/

A fix could be long to implement right now (it seems that we have to plug our own OAuth server).
But you can temporary allow 3rd party cookies in your browser to access the app.

**Comment by iamdey** [comment]
ok. I leave you the responsibility to close or not this issue

**Comment by sriramkp** [comment]
Any Idea, when are you planing to come up with solution, so that we can plan accordingly.

**Comment by bpetetot** [comment]
Hey @iamdey @sriramkp, it should work now. Please can you check it and give me feedback if it works or not ? thx ;)

**Comment by iamdey** [comment]
cmçm

It works for me (for an already created account)
