### ISSUE TITLE
The engine "node" is incompatible with this module. Expected version "8". Got "10.13.0"

### ISSUE THREAD

**Issue by martinbonnin** [bpetetot/conference-hall-beta#355]
I get the following error trying to build the cloud functions. Do I need to install node 8 alongside node 10.13.0 somehow ? (sorry node newbie here...)

    functions$ yarn
    yarn install v1.12.3
    [1/5] Validating package.json...
    error functions@: The engine "node" is incompatible with this module. Expected version "8". Got "10.13.0"
    error Found incompatible module
    info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by martinbonnin** [comment]
I ended up installing node8 and it went fine. It's still a bit painful to need 2 different node environment. Maybe there's a better solution ?
In all cases, I updated the README there if anyone bumps into the same issue => https://github.com/bpetetot/conference-hall/pull/357/files

**Comment by bpetetot** [comment]
Hi martin, sorry I'm a little bit late to answer you.
Indeed we have to use 2 different versions of node with the app and cloud functions.
I'm using `nvm` to manage my node versions, that's why there is a `.nvmrc` in the main app folder and `functions` folder. So I have only to do `nvm use` in app or functions folder, so it will automatically switch to the needed version of node (or install it if you don't have it)
