### ISSUE TITLE
[speaker] the submit and update submission process is confusing

### ISSUE THREAD

**Issue by corinnekrych** [bpetetot/conference-hall-beta#380]
With @fromage We've being discussing some feedback for our RivieraDev speakers when writing a talk proposal, the user does not have to possibility to select which categories and format for her talk. 

Proposal: could we change the submission flow to create a draft submission? At the end of the wizard 2 options: either save as draft (categories and format are saved) or submit.
Therefore the "submit" button that initiate the submission flow could be renamed: "draft submission"

**Comment by bpetetot** [comment]
Maybe I miss something, but during the submission process speakers select a talk, then a category / format during step 2, finally it submit it. The speaker can always come back later, select their talk, update it if necessary, change format / category and update the submission until the CFP is opened.

So you can consider that a proposal is always a draft until the cfp is closed, because the speaker can always update its proposals.

**Comment by corinnekrych** [comment]
It think what really confuses the user is a UX issue. "Submit" button conveys a semantic of a form submit. It's not obvious that clicking the button will bring the wizard to select a conference, the categories and the format. Same for the final submit at the end of the wizard it's not obvious that you can update later one.

Maybe changing the name of the button and adding a tooltip will clear the confusion:
![unspecified-11](https://user-images.githubusercontent.com/1395710/49429097-f95cae80-f7a7-11e8-8c95-c4331d185230.png)

**Comment by bpetetot** [comment]
Yes your right, it's an UX issue, I rename the github issue in that way.

**Comment by bpetetot** [comment]
Closed in favor of discussion in #439
