### ISSUE TITLE
[organizer] sort proposals by "creation date"

### ISSUE THREAD

**Issue by EmmanuelDemey** [bpetetot/conference-hall-beta#416]
When we select "Newest" for sorting, it looks like we are sorting by `updating date`. It would useful to be able to sort by the "creating date" also. 

![image](https://user-images.githubusercontent.com/555768/50403466-006f4f00-079f-11e9-8073-0d403d09ff41.png)

**Comment by bpetetot** [comment]
You're right. Moreover, I think that sort by update date is not necessary, only sort by creation date is revelant. 

**So to do this issue, we have to:**
- Use creation date instead of update date for "Newest" and "Oldest" sorting
- Replace all firestore indexes with update date by the creation dates (see `./config/firestore.indexes.json`)

**Comment by bpetetot** [comment]
Fixed in #523
