### ISSUE TITLE
[organizer] CFP end date is exclusive

### ISSUE THREAD

**Issue by Riduidel** [bpetetot/conference-hall-beta#485]
For Technozaure lille mars 2019, I set as end date Feb 28, and this morning (the Feb 28), it seemed impossible to submit a talk.

Speaker submit button didn't indicated CFP was closed, and i had to do network inspect to discover that.
Could you please

1. Put error message in speaker side to make sure they know their talk is late
2. Make sure on organizer side date is inclusive ? (or at least find a UI way to make sure organizer understands that)

**Comment by ribardo0** [comment]
I guess DevFest Nantes 2019 team had the same problem, today they updated their end date to tomorrow, I don't find it very clear that the end date is exclusive, it would be better to be inclusive, so that speakers may not be disappointed when they try to submit the final day. Even better maybe it should not be a date but a dateTime, so that no confusion could be possible.
