### ISSUE TITLE
Installation documentation does not mention serviceAccount.json

### ISSUE THREAD

**Issue by Ldoppea** [bpetetot/conference-hall-beta#689]
**What is the issue?**

The [Installation page](https://contribute-conference-hall.netlify.com/installation) does not describe how to create `serviceAccount.json`. 

This file is mandatory for using the API.

When not existing, the API throw the following error : 
```
UnhandledPromiseRejectionWarning: Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
```

**Comment by bpetetot** [comment]
You shouldn't need a `serviceAccount.json` because today it is only needed when you have to do a script in node.js. Maybe here you try to execute a private API, this API can only be called from an authenticated user in the application. If you want to play with conference hall apis, you should consider using public APIs
