### ISSUE TITLE
Accessibility: Order of navigation, submit 

### ISSUE THREAD

**Issue by jansche** [bpetetot/conference-hall-beta#854]
**What is the issue?**
![image](https://user-images.githubusercontent.com/22521588/100218848-8c52fe00-2f15-11eb-9a83-7d5079441113.png)
Order of navigate-able elements in this page are difficult. The submit button is greyed out until all required fields are filled. For people on a screen reader this makes the button invisible/unacknowledgeable in the beginning. After filling out the form, the button doesn't get focus after the last field. The user has to navigate back through the form to explore where there could be a button. Not intuitive.

**What is the expected behavior?**
The submit button should be navigated after the last field of the form. 

**What is your environment?**
JAWS screen reader

- OS: Mac and Windows
- Browser: Edge

**Comment by bpetetot** [comment]
Thanks again for the feedback. ;)
Disabled buttons in the app will not be invisible/unacknowledgeable anymore, we use `aria-disabled` instead.
Moreover we have moved the button at the end of the form in order to improve the navigation flow and make it intuitive.
Fix: 845d1bbdde2b6ddd4d3cd5c9becd9ddaef84a73e
